apps/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^add$', views.AddCartView.as_view(), name='add'),  # 添加商品到购物车
    url(r'^$', views.CartInfoView.as_view(), name='info'),  # 购物车页面
    url(r'^update$', views.UpdateCartView.as_view(), name='update'),  # 修改商品数量
    url(r'^delete', views.DeleteCartView.as_view(), name='delete'),  # 删除购物车的商品
]

apps/goods/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from apps.goods import views


urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),  # 商品主页
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),  # 商品详情页面
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$', views.ListView.as_view(), name='list'),  # 商品分页
]

apps/users/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from apps.users import views


urlpatterns = [
    url(r'^register$', views.RegisterView.as_view(), name='register'),  # 注册视图
    url(r'^login$', views.LoginView.as_view(), name='login'),  # 登入视图
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),  # 登入视图
    url(r'^activate/(?P<token>.+)$', views.ActivateView.as_view(), name='activate'),  # 激活用户视图
    url(r'^address$', views.AddressView.as_view(), name='address'),  # 个人中心收货地址
    url(r'^userinfo', views.UserinfoView.as_view(), name='info'),  # 个人中心收货地址
]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^.*$', TemplateView.as_view(template_name="static_ok_index.html")),  # 用户模块
    url(r'^users/', include('users.urls', namespace='users')),  # 用户模块
    url(r'^goods/', include('goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车模块
    url(r'^orders/', include('orders.urls', namespace='orders')),  # 订单模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View
from django_redis import get_redis_connection
from goods.models import GoodsSKU


class AddCartView(View):
    """添加商品到购物车功能"""

    def post(self, request):
        # 获取添加到购物车的商品和数量
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'msg': '购物车参数不全'})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'msg': '不存在该商品'})

        # 判断商品数量是否正确
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'code': 3, 'msg': e})

        # 判断库存是否足够
        if count > sku.stock:
            return JsonResponse({'code': 4, 'msg': '库存不足'})

        user = request.user
        # 用户登入的情况下
        if user.is_authenticated():
            # 使用哈希格式来存储数据user_id:{'sku_id1':count1, 'sku_id:count2}
            redis_conn = get_redis_connection('default')
            # 存到redis的购物车数量=之前的数量+现在添加数量
            origin_count = redis_conn.hget('cart_%s' % user.id, sku_id)
            if origin_count is not None:
                count += int(origin_count)
            # 把数据保存到redis
            redis_conn.hset('cart_%s' % user.id, sku_id, count)
        # 用户没有登入的情况下,把数据保存到浏览器
        else:
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}

            # 如果已经存在该商品，累加数量
            if sku_id in cart_dict:
                origin_count = cart_dict.get(sku_id)
                count += origin_count

            cart_dict[sku_id] = count

        # 查询购物车数量,登入从redis中获取，未登入从cookie获取
        cart_num = 0
        if user.is_authenticated():
            user = request.user
            redis_conn = get_redis_connection('default')
            cart_dict = redis_conn.hgetall('cart_%s' % user.id)

        for value in cart_dict.values():
            cart_num += int(value)

        response = JsonResponse({'code': 0, 'msg': '添加成功', 'cart_num': cart_num})

        if not user.is_authenticated():
            cart_json = json.dumps(cart_dict)
            response.set_cookie('cart', cart_json)

        return response


class CartInfoView(View):
    """购物车页面"""

    def get(self, request):
        # 用户登入，从redis中获取数据， 用户未登入，从浏览器cookie获取数据
        user = request.user

        if user.is_authenticated():
            redis_conn = get_redis_connection('default')
            # 获取所有的数据
            cart_dict = redis_conn.hgetall('cart_%s' % user.id)
        else:
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}

        total_count = 0  # 用于计算全部商品的数量
        total_amount = 0  # 用于计算全部商品的总价
        skus = []

        # 遍历所有的商品
        for sku_id, count in cart_dict.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                continue

            count = int(count)
            amount = count * sku.price
            sku.count = count
            sku.amount = amount
            total_amount += amount
            total_count += count
            skus.append(sku)

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_amount': total_amount
        }

        return render(request, 'cart.html', context)


class UpdateCartView(View):
    """购物车页面商品的增加和修改"""
    def post(self, request):
        user = request.user

        # 获取被修改商品的id和数量
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'msg': '参数不全'})
        # 查询商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'msg': '不存在该商品'})
        # 检查商品数量是否正确
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'code': 3, 'msg': '%s' % e})
        # 判断商品的库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'msg': '数量超出库存'})

        # 通过校验，更新购物车的商品数据
        if user.is_authenticated():  # 用户登入了
            redis_conn = get_redis_connection('default')
            redis_conn.hset('cart_%s' % user.id, sku_id, count)
            return JsonResponse({'code': 0, 'msg': '更新购物车成功'})
        else:  # 用户未登入,修改浏览器cookies中的数据并保存
            cart_json = request.COOKIES.get('cart')
            if cart_json:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}
            cart_dict[sku_id] = count
            response = JsonResponse({'code': 0, 'msg': '更新购物车成功'})

            response.set_cookie('cart', json.dumps(cart_dict))
            return response


class DeleteCartView(View):
    """删除购物车中的商品"""
    def post(self, request):
        user = request.user

        # 获取被删除的商品id
        sku_id = request.POST.get('sku_id')

        # 校验数据
        if not sku_id:
            return JsonResponse({'code': 1, 'msg': '参数错误'})

        # 用户登入，修改redis中的数据
        if user.is_authenticated():
            redis_conn = get_redis_connection('default')
            redis_conn.hdel('cart_%s' % user.id, sku_id)
            return JsonResponse({'code': 0, 'msg': '删除成功'})
        # 用户未登入，从浏览器cookies中删除商品的数据
        else:
            cart_json = request.COOKIES.get('cart')
            if cart_json:
                cart_dict = json.loads(cart_json)
                if sku_id in cart_dict:
                    del cart_dict[sku_id]
                    response = JsonResponse({'code': 0, 'msg': '删除成功'})
                    response.set_cookie('cart', json.dumps(cart_dict))
                    return response

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
{#					<a href="{% url 'cart:info' %}">我的购物车</a>#}
					<a href="#">我的购物车</a>
					<span>|</span>
{#					<a href="{% url 'orders:info' 1 %}">我的订单</a>#}
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
{#			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>#}
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in categorys %}
                        {# http://127.0.0.1:8000/goods/list/categoryid/1?sort=price #}
                        <li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="#">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
                {# http://127.0.0.1:8000/goods/list/categoryid/1?sort=price #}
				<a href="{% url 'goods:list' category.id 1 %}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="detail.html">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ sku.price }}</span>
                            <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
				    </li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' category.id skus_page.previous_page_number %}">上一页</a>
                {% endif %}

                {% for item in page_list %}
                    <a href="{% url 'goods:list' category.id item %}" {% if item == skus_page.number %}class="active"{% endif %}>{{ item }}</a>
                {% endfor %}

				{% if skus_page.has_next %}
                    <a href="{% url 'goods:list' category.id skus_page.next_page_number %}">下一页</a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock body %}

templates/place_order.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-提交订单{% endblock %}

{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
        <div class="search_con fr">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" value="搜索">
            </form>
        </div>
    </div>
{% endblock %}

{% block body %}
    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            {% if address %}

                <dd><input type="radio" name="address_id" value="{{ address.id }}"
                           checked="">{{ address.receiver_name }} {{ address.detail_addr }} {{ address.receiver_mobile }}
                </dd>
            {% else %}
                <dd><input type="radio" name="address_id" value="" checked="">请添加地址</dd>
            {% endif %}
        </dl>
        <a href="{% url 'users:address' %}" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" value="1" checked>
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style" value="2">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style" value="2">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style" value="2">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for sku in skus %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="{{ sku.default_image.url }}"></li>
                <li class="col03">{{ sku.name }}</li>
                <li class="col04">{{ sku.unit }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">{{ sku.count }}</li>
                <li class="col07">{{ sku.amount }}元</li>
            </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_sku_amount }}元</b></div>
            <div class="transit">运费：<b>{{ trans_cost }}元</b></div>
            <div class="total_pay">实付款：<b>{{ total_amount }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn">提交订单</a>
    </div>


{% endblock %}

{% block footer %}
    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>

        <div class="mask"></div>
    </div>
{% endblock %}

{% block bottom_files %}
    <script type="text/javascript">
        $('#order_btn').click(function () {
            // 地址id
            var address_id = $('input[name="address_id"]').val();
            if (address_id == "") {
                alert("请先编辑收货地址!");

            }
            else {
                var order_data = {
                    address_id: address_id,
                    pay_method: $('input[name="pay_style"]:checked').val(),
                    sku_ids: '{{ sku_ids }}',
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                };
                console.log(order_data);
                $.ajax({
                    url: "/orders/commit",
                    data: order_data,
                    type: 'post',
                    dataType: 'json'
                }).done(function (data) {
                    if (1 == data.code) {
                        // 用户登录
                        location.href = '/users/login';
                    } else if (5 == data.code) {
                        alert("库存不足，请修改订单！");
                    } else if (0 == data.code) {
                        // 下单成功
                        $('.popup_con').fadeIn('fast', function () {
                            setTimeout(function () {
                                $('.popup_con').fadeOut('fast', function () {
                                   //alert("成功");
                                    location.href = '/orders/1';
                                });
                            }, 3000)
                        });
                    }
                }).fail(function () {
                    alert('下单失败')
                })
            }
        });
    </script>
{% endblock %}

templates/user_center_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
            <form method="get" action="/search/">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock %}

templates/user_center_info.html
{% extends 'user_center_base.html' %}

{% block body %}

	<div class="main_con clearfix">
    {% load staticfiles %}
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
							<li><span>联系地址：</span>{{ address.detail_addr }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                    {% for sku in skus %}
                        <li>
                            <a href="{% static 'detail.html' %}"><img src="{{ sku.default_image.url }}"></a>
                            <h4><a href="{% static 'detail.html' %}">{{ sku.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ sku.price }}</span>
                                <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
			    </ul>
		    </div>
		</div>
	</div>

{% endblock %}

templates/user_center_order.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'users:info' %}">· 个人信息</a></li>
                <li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'users:address' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress">{{ order.status_name }}</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for sku in order.skus %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02">{{ sku.name }}<em>{{ sku.price }}/{{ sku.unit }}</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                    <li class="col04">{{ sku.amount }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br/>（含运费{{ order.trans_cost }}元）</td>
                        <td width="15%">{{ order.pay_method_name }}</td>
                        <td width="15%"><a href="javascript:;" order_id="{{ order.order_id }}"
                                           order_status="{{ order.status }}" class="oper_btn">
                            {{ order.status_name }}
                        </a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                {% if orders.has_previous %}
                    <a href="{% url 'orders:info' orders.previous_page_number %}">上一页</a>
                {% endif %}
                {% for p in page_list %}
                    <a href="{% url 'orders:info' p %}" {% if p == order.number %}class="active"{% endif %}>{{ p }}</a>
                {% endfor %}
                {% if orders.has_next %}
                    <a href="{% url 'orders:info' orders.next_page_number %}">下一页></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block bottom_files %}

    <script type="text/javascript">
        //点击按钮去支付 或者去评论
        $('.oper_btn').click(function () {
            var order_id = $(this).attr("order_id"); //取订单号
            var order_status = $(this).attr("order_status"); //取状态

            order_status = parseInt(order_status);
            //如果状态是待支付
            if (1 == order_status) {
                // 表示订单待支付，向django后端索要支付宝的支付链接
                var req_data = {
                    order_id: order_id,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                };
                $.ajax({
                    url: '/orders/pay',
                    type: 'post',
                    data: req_data,
                    dataType: 'json'
                }).done(function (data) {
                    if (1 == data.code) {
                        // 用户未登录
                        console.log(data.code)
                        location.href = "/users/login";
                    } else if (0 == data.code) {
                        // 成功拿到了支付连接，开启一个新页面，让用户在新页面进行支付
                        window.open(data.url);
                        $.ajax({
                            url: '/orders/check_pay',
                            type: 'get',
                            data: {order_id: order_id},
                            dataType: 'json'
                        }).done(function (resp_data) {
                            if (0 == resp_data.code) {
                                // 支付成功
                                alert("支付成功");
{#                                当前页面刷新#}
                                location.reload();
                            } else {
                                alert(resp_data.msg);
                            }
                        }).fail(function () {
                            alert('支付失败');
                            console.log()
                        })
                    } else {
                        alert(data.msg);
                    }
                }).fail(function () {
                    alert('网路异常')
                })

            } else if (2 == order_status) {
             //else if (4 == order_status) {
                //去评论
                location.href = ("/orders/comment/" + order_id)
            }
        });
    </script>
{% endblock %}

templates/user_center_site.html
{% extends 'user_center_base.html' %}

{% block body %}
<body>
	<div class="main_con clearfix">
        {% load staticfiles %}
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{# <dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd> #}
                        <dd>{{ address.detail_addr }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="recv_name">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="recv_mobile">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock %}